### ISSUE TITLE
Version 2.5.2 is undownloadable through eclipse

### ISSUE THREAD

**Issue by RCosta01** [innoventsolutions/innoventsolutions.github.io#7]
When downloading through the normal URL it now returns the following error:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.reporting, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: http://innoventsolutions.github.io/2.5.2/plugins/birt.controls.lib_2.5.2.4.jar.
http://innoventsolutions.github.io/2.5.2/plugins/birt.controls.lib_2.5.2.4.jar
Artifact not found: http://innoventsolutions.github.io/2.5.2/plugins/birt.controls.lib.ui_2.5.2.2.jar.
http://innoventsolutions.github.io/2.5.2/plugins/birt.controls.lib.ui_2.5.2.2.jar
Artifact not found: http://innoventsolutions.github.io/2.5.2/plugins/birt.functions.lib_2.6.1.12.jar.
http://innoventsolutions.github.io/2.5.2/plugins/birt.functions.lib_2.6.1.12.jar
Artifact not found: http://innoventsolutions.github.io/2.5.2/features/birt.controls.lib.feature_2.5.2.3.jar.
http://innoventsolutions.github.io/2.5.2/features/birt.controls.lib.feature_2.5.2.3.jar
Artifact not found: http://innoventsolutions.github.io/2.5.2/features/birt.functions.lib.feature_2.6.1.12.jar.
http://innoventsolutions.github.io/2.5.2/features/birt.functions.lib.feature_2.6.1.12.jar

I believe this might be related to the latest commit which removed all the .jar files

**Comment by ZwoCa** [comment]
I can confirm this, JAR files are not present any more and Eclipse will not therefore fail to install with above message.

**Comment by SteveSchafer-Innovent** [comment]
Should be fixed now.  Please try again.
